/**
 * Marcas e modelos mais comuns na frota brasileira, para o seletor do alerta.
 * Lista local (funciona sem internet); o usuário também pode digitar qualquer outro.
 */
const grupo = (titulo: string, marca: string, modelos: string[]) => ({
  titulo,
  itens: modelos.map((m) => `${marca} ${m}`),
});

export const MODELOS_GRUPOS: { titulo: string; itens: readonly string[] }[] = [
  grupo('Volkswagen', 'VW', ['GOL', 'VOYAGE', 'FOX', 'UP!', 'POLO', 'VIRTUS', 'T-CROSS', 'NIVUS', 'TAOS', 'SAVEIRO', 'AMAROK', 'JETTA', 'GOLF', 'TIGUAN', 'SPACEFOX', 'PARATI', 'KOMBI']),
  grupo('Fiat', 'FIAT', ['UNO', 'MOBI', 'ARGO', 'CRONOS', 'PALIO', 'PALIO WEEKEND', 'SIENA', 'GRAND SIENA', 'STRADA', 'TORO', 'PULSE', 'FASTBACK', 'IDEA', 'PUNTO', 'DOBLO', 'FIORINO', 'DUCATO', 'TITANO']),
  grupo('Chevrolet', 'CHEVROLET', ['ONIX', 'ONIX PLUS', 'PRISMA', 'CELTA', 'CORSA', 'CLASSIC', 'COBALT', 'SPIN', 'TRACKER', 'S10', 'MONTANA', 'CRUZE', 'AGILE', 'EQUINOX', 'TRAILBLAZER', 'ASTRA', 'VECTRA', 'MERIVA', 'ZAFIRA']),
  grupo('Ford', 'FORD', ['KA', 'KA SEDAN', 'FIESTA', 'FOCUS', 'ECOSPORT', 'RANGER', 'FUSION', 'COURIER', 'TERRITORY', 'MAVERICK', 'BRONCO SPORT']),
  grupo('Hyundai', 'HYUNDAI', ['HB20', 'HB20S', 'CRETA', 'TUCSON', 'IX35', 'SANTA FE', 'HR']),
  grupo('Toyota', 'TOYOTA', ['COROLLA', 'COROLLA CROSS', 'ETIOS', 'YARIS', 'HILUX', 'SW4', 'RAV4']),
  grupo('Honda (carros)', 'HONDA', ['CIVIC', 'CITY', 'FIT', 'HR-V', 'WR-V', 'CR-V']),
  grupo('Renault', 'RENAULT', ['SANDERO', 'SANDERO STEPWAY', 'LOGAN', 'KWID', 'DUSTER', 'OROCH', 'CAPTUR', 'CLIO', 'SYMBOL', 'MASTER']),
  grupo('Nissan', 'NISSAN', ['KICKS', 'VERSA', 'MARCH', 'SENTRA', 'FRONTIER', 'LIVINA']),
  grupo('Jeep', 'JEEP', ['RENEGADE', 'COMPASS', 'COMMANDER']),
  grupo('Peugeot', 'PEUGEOT', ['208', '2008', '207', '206', '308', '3008', 'PARTNER']),
  grupo('Citroën', 'CITROEN', ['C3', 'C3 AIRCROSS', 'C4 CACTUS', 'C4 LOUNGE', 'BERLINGO', 'JUMPY']),
  grupo('Mitsubishi', 'MITSUBISHI', ['L200 TRITON', 'PAJERO', 'ASX', 'OUTLANDER', 'ECLIPSE CROSS']),
  grupo('Caoa Chery', 'CAOA CHERY', ['TIGGO 5X', 'TIGGO 7', 'TIGGO 8', 'ARRIZO 6']),
  grupo('BYD', 'BYD', ['DOLPHIN', 'DOLPHIN MINI', 'SONG PLUS', 'SONG PRO', 'SEAL', 'YUAN PLUS', 'KING']),
  grupo('GWM', 'GWM', ['HAVAL H6', 'ORA 03']),
  grupo('Kia', 'KIA', ['SPORTAGE', 'CERATO', 'SORENTO', 'PICANTO', 'BONGO']),
  {
    titulo: 'Importados premium',
    itens: ['BMW 320I', 'BMW X1', 'MERCEDES-BENZ C 180', 'MERCEDES-BENZ CLASSE A', 'AUDI A3', 'AUDI Q3', 'VOLVO XC60'],
  },
  {
    titulo: 'Utilitários e caminhões',
    itens: [
      'MERCEDES-BENZ SPRINTER',
      'IVECO DAILY',
      'VW DELIVERY',
      'MERCEDES-BENZ ACCELO',
      'VOLVO FH',
      'SCANIA R 450',
    ],
  },
  grupo('Motos Honda', 'HONDA', [
    'CG 160 TITAN',
    'CG 160 FAN',
    'CG 160 START',
    'CG 150 TITAN',
    'CG 125 FAN',
    'BIZ 125',
    'BIZ 110I',
    'POP 110I',
    'NXR 160 BROS',
    'XRE 300',
    'XRE 190',
    'SAHARA 300',
    'CB 300F TWISTER',
    'CB 250F TWISTER',
    'CB 500F',
    'PCX 160',
    'ELITE 125',
    'ADV 160',
  ]),
  grupo('Motos Yamaha', 'YAMAHA', [
    'FAZER FZ25',
    'FACTOR 150',
    'YBR 150',
    'XTZ 150 CROSSER',
    'XTZ 250 LANDER',
    'NMAX 160',
    'NEO 125',
    'FLUO 125',
    'XMAX 250',
    'MT-03',
    'MT-07',
    'R3',
  ]),
  {
    titulo: 'Outras motos',
    itens: [
      'SUZUKI YES 125',
      'SUZUKI INTRUDER 125',
      'SUZUKI BURGMAN 125',
      'KAWASAKI NINJA 400',
      'KAWASAKI Z400',
      'KAWASAKI Z900',
      'SHINERAY JET 50',
      'SHINERAY PHOENIX 50',
      'SHINERAY WORKER 125',
      'HAOJUE DK 150',
      'HAOJUE DR 160',
      'HAOJUE NK 150',
      'BMW G 310 R',
      'BMW R 1250 GS',
    ],
  },
];
